bhchen2001-proposal-submission
yungyuc/nsd_24sp pull request #45
Opened 2024-03-30 13:38 UTC by bhchen2001

---
A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

2024-03-31 08:42 UTC, yungyuc requested changes
- [x] Correct typo (e.g., Voronoi)
- [x] Clarify familiarity with k-d tree
- [x] Clarify familiarity wth Fortune's algorithm
- [ ] Clarify familiarity with threading
- [ ] Briefly describe the data structure for Voronoi diagram
- [ ] Reconsider testing in your plan

It baffles to name your branch exactly the same as the upstream branch (project), but it's too late for you to change. Please avoid it in the future.

When you are ready for the next review, leave a comment, clearly write down something like "I am ready, please review again".

2024-03-31 08:42 UTC, yungyuc commented on project/README.rst
> +2. `bhchen2001 <https://github.com/bhchen2001>`__ for
Beautiful

2024-03-31 08:42 UTC, yungyuc commented on project/bhchen2001/README.rst
> +3. ``Fortune's algorithm`` for generating the vonoroi diagram independently at each thread on the blocks assigned to it.
This requires familiarity with the Fortune algorithm and multi-threading code development.

How familiar you are with the algorithm?

How familiar you are with a threading library?  Which one it is?

2024-03-31 08:42 UTC, yungyuc commented on project/bhchen2001/README.rst
> +2. K-d tree for decomposing the points into different blocks.
Did you have experience with a spatial index?  Are you familiar with any existing source code implementing a k-d tree?

A k-d tree alone suffices a term project.

2024-03-31 08:42 UTC, yungyuc commented on project/bhchen2001/README.rst
> +The ``C++`` API::
You need a data structure to hold the Voronoi diagram, i.e., your `VoronoiDiagram` class.  Please briefly describe the data structure.

2024-03-31 08:42 UTC, yungyuc commented on project/bhchen2001/README.rst
> +Parallel Vonoroi Diagram
It's Voronoi diagram, not "Vonoroi": https://mathworld.wolfram.com/VoronoiDiagram.html

2024-03-31 08:42 UTC, yungyuc commented on project/bhchen2001/README.rst
> +* Week 1 (04/08): Research on ``fortune's algorithm`` and ``k-d tree``.
I recommend you scale down the scope.  You are proposing to do two things: Fortune's algorithm for making a Voronoi diagram and k-d tree for indexing the geometry.  You are also proposing to parallelize the code.  While it is possible to prototype all of them in 8 weeks, it is very difficult to engineer it well.

If you insist to do everything, it's fine, but please find me at [sciwork #nsd channel](https://discord.gg/tZsUnx4XmB) to discuss before you make the decision.

2024-03-31 08:42 UTC, yungyuc commented on project/bhchen2001/README.rst
> +  * Testing and debugging for the parallel version.
Putting testing at such a late stage tells me that you do not have experience to use testing for productivity.  Please discuss with me or the sciwork community for how testing can help you, and move it earlier in your plan.

2024-04-14 13:09 UTC, yungyuc commented
@bhchen2001 Please resolve the conflict and update the proposal.

2024-04-19 12:10 UTC, bhchen2001 commented
@yungyuc 
I scaled down my topic from 'parallel Voronoi diagram' to 'searching based on kd-tree' and advanced the testing process in the development phase. Please review it again and let me know where improvements are needed.

2024-04-20 08:01 UTC, yungyuc approved these changes
This is OK

2024-04-20 08:01 UTC, yungyuc commented on project/bhchen2001/README.rst
> +            std::vector<double> coordinates;
`std::vector` requires dynamic memory allocation and it will slows down your system.  Be aware of this thing.

2024-04-20 08:01 UTC, yungyuc commented on project/bhchen2001/README.rst
> +  * Testing and refactoring for ``Insert`` and ``Delete`` functions
Testing on the 4th week is not taking the most productivity to you, but not too bad.

2024-04-20 08:01 UTC, merged