Lianghy0326-proposal-submission
yungyuc/nsd_24sp pull request #50
Opened 2024-03-31 08:14 UTC by Lianghy0326

---
A good PR should include the following parts:

- [ ] Provide a clear title
- [ ] Provide meaningful descriptions in the PR and the commit logs
- [ ] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [ ] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [ ] Exclude irrelevant files, such as binaries, text files, or dot files
- [ ] Make sure tests/CI pass

2024-03-31 09:14 UTC, yungyuc requested changes
- [ ] You missed an entry in `project/README.rst` as [requested](https://github.com/yungyuc/nsdhw_24sp/blob/567be93bc63a6fb1c2c55b8faf5825172daeaba5/project/README.rst?plain=1#L22)
- [x] Discuss ease of presentation
- [x] 79-char line width
- [ ] Test earlier for productivity

When you are ready for the next review, leave a comment, clearly write down something like "I am ready, please review again".

2024-03-31 09:14 UTC, yungyuc commented on project/Lianghy0326/Readme.rst
> +Pathfinding is a fundamental problem in computer science and has numerous applications in various domains, including robotics, video games, and network routing.
While it is fundamental, it is not so interesting for you to easily make a presentation.  If you are interested in computer vision or graphics, a topic in those areas may be easier to present.

If you are not 100% sure about what you want to do, please find me at [sciwork #nsd channel](https://discord.gg/tZsUnx4XmB) to discuss more.

2024-03-31 09:14 UTC, yungyuc commented on project/Lianghy0326/Readme.rst
> +In this project, we aim to explore and implement different pathfinding algorithms, such as A* (A-star), Depth-First Search (DFS), and possibly others, to address the diverse needs of users in path pl
It is bad to use one line for a single paragraph, for it makes the lines to be too long. It is hard to add comments at specific location for a long line. Please change to 79-char width.

2024-04-14 13:08 UTC, yungyuc commented
@Lianghy0326 Please update the proposal.

2024-04-14 16:39 UTC, Lianghy0326 commented
Already update the proposal project.
I have changed the proposal topic from "path-finding" to "ODE solver" topic.
thanks teacher.

Lianghy0326

Yung-Yu Chen ***@***.***> 於 2024年4月14日 週日 下午9:08寫道：

> @Lianghy0326 <https://github.com/Lianghy0326> Please update the proposal.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yungyuc/nsdhw_24sp/pull/50#issuecomment-2054056859>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBYY2EGKRBBMHQ37WJ6GANLY5J5WRAVCNFSM6AAAAABFQHD3N6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANJUGA2TMOBVHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-19 00:10 UTC, yungyuc requested changes
- [ ] (Again) You missed an entry in `project/README.rst` as [requested](https://github.com/yungyuc/nsdhw_24sp/blob/567be93bc63a6fb1c2c55b8faf5825172daeaba5/project/README.rst?plain=1#L22)
- [ ] Please find me in scisprint or meetup or schedule discussions for your project.  It's not in a good shape and you need help of critical analysis.

When you are ready for the next review, leave a comment, clearly write down something like "I am ready, please review again".  Do not forget this when you participate in a code review (and/or PR).

2024-04-19 00:10 UTC, yungyuc commented on project/Lianghy0326/Readme.md
> +Design an intelligent C++ solver that automatically selects the optimal solving method for differential equation (DE) problems.
This is way longer than 79 chars.  You should configure your editor to format your text.

You have most of the lines to be short enough for review, so it's not too bad.  Please fix the line width when you update for other things.

2024-04-19 00:10 UTC, yungyuc commented on project/Lianghy0326/Readme.md
> +# DE
I like short project name 🙂

2024-04-19 00:10 UTC, yungyuc commented on project/Lianghy0326/Readme.md
> +- Week 7 (05/20): Test and debug
Still so late for testing.  It's dangerous for your progress.

2024-05-07 14:16 UTC, yungyuc commented
> When you are ready for the next review, leave a comment, clearly write down something like "I am ready, please review again". Do not forget this when you participate in a code review (and/or PR).

@Lianghy0326 I have not heard from you.  Please address the points I made or I cannot grade.

2024-05-08 08:13 UTC, Lianghy0326 commented
I am ready, please review again
I have fixed my readme.rst file in my project

2024-05-08 09:08 UTC, Lianghy0326 commented
I am ready, please review again

2024-05-11 02:12 UTC, yungyuc requested changes
- [ ] (Again twice) You missed an entry in `project/README.rst` as [requested](https://github.com/yungyuc/nsdhw_24sp/blob/567be93bc63a6fb1c2c55b8faf5825172daeaba5/project/README.rst?plain=1#L22)
- [ ] I did not hear from you anywhere except the late comments in this PR.  Please find me to discuss your progress.
- [ ] Your PR includes unrelated history.  Please get rid of it.

2024-05-11 02:12 UTC, yungyuc commented on hw4/.gitignore
Your proposal PR should not include anything else.  Please rebase to fix the wrong history.

2024-05-12 12:21 UTC, Lianghy0326 commented
I'm unsure how to resolve the issue with the "missed entry in project/README.rst."

Additionally, I have made modifications to my project content to address the topic's shortcomings and would appreciate critical analysis. If the revisions are satisfactory, I would like to discuss my topic next week after class or other time.

Thank you teacher.

ViviLiang

2024-05-12 13:08 UTC, yungyuc commented
Please read https://github.com/yungyuc/nsdhw_24sp/blob/567be93bc63a6fb1c2c55b8faf5825172daeaba5/project/README.rst?plain=1#L22 as I mentioned in the previous comments.

I think it's a good idea to have a F2F discussion.  We can do it during the lecture.

2024-05-19 01:44 UTC, merged