ravencyan-proposal-submission
yungyuc/nsd_24sp pull request #53
Opened 2024-03-31 13:22 UTC by ravencyan

---
A good PR should include the following parts:

- [ ] Provide a clear title
- [ ] Provide meaningful descriptions in the PR and the commit logs
- [ ] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [ ] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [ ] Exclude irrelevant files, such as binaries, text files, or dot files
- [ ] Make sure tests/CI pass

2024-04-02 10:47 UTC, yungyuc requested changes
- [ ] You missed an entry in `project/README.rst` as [requested](https://github.com/yungyuc/nsdhw_24sp/blob/567be93bc63a6fb1c2c55b8faf5825172daeaba5/project/README.rst?plain=1#L22)
- [ ] Please add an entry for this PR in E3 (I did not see it)
- [ ] Specify the types or constraints of the equations to solve for.
- [ ] Please beef up your descriptions of architecture.

It baffles to name your branch exactly the same as the upstream branch (`project`), but it's too late for you to change.  Please avoid it in the future.

When you are ready for the next review, leave a comment, clearly write down something like "I am ready, please review again".

2024-04-02 10:47 UTC, yungyuc commented on project/ravencyan/README.rst
> +When it comes to finding the solution of equations, root finding algorithms are
What kind of equations will you solve for?

2024-04-02 10:47 UTC, yungyuc commented on project/ravencyan/README.rst
> +The program will provide an prompt for the user to input an equation in the format:
Please beef up your descriptions of architecture.

2024-04-02 10:47 UTC, yungyuc commented on project/ravencyan/README.rst
> +* Week 7 (05/20): Final check for any potential bugs, update the documentation to the final version.
Debugging should be part of the iterations of implementation.

2024-04-14 13:08 UTC, yungyuc commented
@ravencyan Please update the proposal and E3.

2024-05-07 14:23 UTC, yungyuc commented
> @ravencyan Please update the proposal and E3.

@ravencyan This is a reminder that I cannot grade your proposal since the points have not been fully addressed.

2024-05-07 15:00 UTC, ravencyan commented
Dear professor,

Sorry I’m late, I will update my proposal as soon as possible!

Best Regards,
吳玟叡

Yung-Yu Chen ***@***.***>於 2024年5月7日 週二，下午10:23寫道：

> @ravencyan <https://github.com/ravencyan> Please update the proposal and
> E3.
>
> @ravencyan <https://github.com/ravencyan> This is a reminder that I
> cannot grade your proposal since the points have not been fully addressed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yungyuc/nsdhw_24sp/pull/53#issuecomment-2098530880>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL7G5XAYN6QVSF2Z6HM37SLZBDPVZAVCNFSM6AAAAABFQNRCQWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJYGUZTAOBYGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-19 01:43 UTC, merged