Ananaee-proposal-submission
yungyuc/nsd_24sp pull request #56
Opened 2024-03-31 16:26 UTC by Ananaee

---
A good PR should include the following parts:

- [x] Provide a clear title
- [x] Provide meaningful descriptions in the PR and the commit logs
- [x] Name your branch like ``<github-user-name>-hw#``, e.g., ``myname-hw2-attempt1``
- [x] Merge from your specific branch (***not master***) to the `hw*` branch (***not master***, again)
- [x] Exclude irrelevant files, such as binaries, text files, or dot files
- [x] Make sure tests/CI pass

2024-04-02 11:12 UTC, yungyuc requested changes
- [ ] 79-char line width
- [ ] Rethink testing

It baffles to name your branch exactly the same as the upstream branch (`project`), but it's too late for you to change.  Please avoid it in the future.

When you are ready for the next review, leave a comment, clearly write down something like "I am ready, please review again".

2024-04-02 11:12 UTC, yungyuc commented on project/Ananaee/README.md
> +Project name: `GameStrategy <https://github.com/Ananaee/GameStrategy`
The repository is not available.  And the rst link format is wrong.

2024-04-02 11:12 UTC, yungyuc commented on project/Ananaee/README.md
> +GameStrategy
I like the name.

2024-04-02 11:12 UTC, yungyuc commented on project/Ananaee/README.md
> +GameStrategy is a project aimed at developing AI agents for strategy games that utilize Voronoi diagrams and the Minimax algorithm for tactical decision-making.
A single line is used for a paragraph and it is too long. It is hard to add comments at specific location for a long line. Please change to 79-char width.

2024-04-02 11:12 UTC, yungyuc commented on project/Ananaee/README.md
> +Strategy games often require intelligent decision-making by AI agents to compete effectively against human players or other AI opponents. One common challenge in such games is to make optimal decisio
Are you talking about a 2D or 3D game?

2024-04-02 11:12 UTC, yungyuc commented on project/Ananaee/README.md
> +- Week 6 (5/13): Performance test and bug fix.
No other tests?  And testing late slows you down.  Please research how to test-as-you-code and rethink what is the role of testing in your development.

2024-04-14 13:07 UTC, yungyuc commented
@Ananaee please update your proposal

2024-04-24 08:09 UTC, Ananaee commented
I am ready, please review again.

2024-04-27 01:27 UTC, yungyuc approved these changes
Look forward to your code.

2024-04-27 01:27 UTC, yungyuc commented on project/Ananaee/README.md
> +- Week 6 (5/13): Performance test and bug fix.
Let's not resolve conversation in a PR with me.  It makes it difficult to keep track of discussions.

2024-04-27 01:27 UTC, yungyuc commented on project/Ananaee/README.md
> +- Week 3 (4/22):  Develop Minimax algorithm with alpha-beta pruning and test.
I hope you already have some code along with minimal tests.  If you have not, please try make some progress before too late.  I have not see any code pushed to your project repository https://github.com/Ananaee/GameStrategy .  If your code is in your local copy, please seriously consider to push it to publish.

Your code needs to be in public before I have an opportunity to help you.

2024-04-27 01:29 UTC, merged